const state={projects:[],project:null,tasks:[]};
const $=id=>document.getElementById(id);
const statuses=[['backlog','Backlog'],['in_progress','In progress'],['review','In review'],['done','Done']];
async function api(path,options={}){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...options});if(!res.ok){let data={};try{data=await res.json()}catch{}throw new Error(data.error||`Request failed (${res.status})`)}return res.status===204?null:res.json()}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3000)}
function node(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el}
function metric(label,value,foot){const el=node('div','metric');el.append(node('div','metric-label',label),node('div','metric-value',value),node('div','metric-foot',foot));return el}
async function loadProjects(){state.projects=await api('/api/projects');const select=$('projectSelect');select.replaceChildren();for(const p of state.projects){const opt=node('option',null,p.name);opt.value=p.id;select.append(opt)}const saved=Number(localStorage.getItem('flowboard_project'));state.project=state.projects.find(p=>p.id===saved)||state.projects[0]||null;if(state.project)select.value=state.project.id;await renderProject()}
async function renderProject(){const p=state.project;$('empty').hidden=!!p;$('board').hidden=!p;$('metrics').hidden=!p;$('newTask').disabled=!p;$('projectTitle').textContent=p?p.name:'Your projects';$('crumbProject').textContent=p?p.name:'Projects';$('repoLabel').textContent=p?.repo?`↗ ${p.repo}`:'';if(!p)return;localStorage.setItem('flowboard_project',p.id);const [tasks,metrics]=await Promise.all([api(`/api/projects/${p.id}/tasks`),api(`/api/projects/${p.id}/metrics`)]);state.tasks=tasks;renderMetrics(metrics);renderBoard()}
function renderMetrics(m){$('metrics').replaceChildren(metric('Total tasks',m.total,'Across all stages'),metric('In progress',m.in_progress,'Active delivery'),metric('In review',m.review,'Awaiting merge'),metric('Completed',`${Math.round(m.completion)}%`,`${m.done} shipped · ${m.avg_cycle_days}d avg cycle`))}
function renderBoard(){const board=$('board');board.replaceChildren();for(const [status,label] of statuses){const col=node('div','column');col.dataset.status=status;const head=node('div','column-head');head.append(node('span','column-dot'),node('span',null,label),node('span','count',state.tasks.filter(t=>t.status===status).length));col.append(head);for(const t of state.tasks.filter(t=>t.status===status)){const card=node('article','card');card.draggable=true;card.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',String(t.id)));card.addEventListener('click',()=>showDetail(t));const top=node('div','card-top');top.append(node('span','card-key',`${state.project.key}-${t.id}`),node('span',`priority ${t.priority}`,t.priority));card.append(top,node('div','card-title',t.title));if(t.description)card.append(node('div','card-description',t.description.length>90?t.description.slice(0,90)+'…':t.description));const bottom=node('div','card-bottom');bottom.append(node('span',null,new Date(t.created_at).toLocaleDateString()));const right=node('div','card-bottom-right');if(t.pr_number)right.append(node('span','pr',`PR #${t.pr_number}`));if(t.assignee)right.append(node('span','avatar',t.assignee[0].toUpperCase()));bottom.append(right);card.append(bottom);col.append(card)}col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drag-over')});col.addEventListener('dragleave',()=>col.classList.remove('drag-over'));col.addEventListener('drop',async e=>{e.preventDefault();col.classList.remove('drag-over');const id=Number(e.dataTransfer.getData('text/plain'));const task=state.tasks.find(t=>t.id===id);if(!task||task.status===status)return;try{await api(`/api/tasks/${id}`,{method:'PATCH',body:JSON.stringify({status})});await renderProject();toast(`Moved to ${label}`)}catch(err){toast(err.message)}});board.append(col)}}
async function showDetail(t){$('detailTitle').textContent=t.title;$('detailDescription').textContent=t.description||'No description yet.';const meta=$('detailMeta');meta.replaceChildren(node('span',null,`${state.project.key}-${t.id}`),node('span',null,t.status.replaceAll('_',' ')),node('span',null,t.priority),node('span',null,t.assignee||'Unassigned'));if(t.pr_url){const a=node('a',null,`GitHub PR #${t.pr_number} ↗`);a.href=t.pr_url;a.target='_blank';a.rel='noopener noreferrer';meta.append(a)}const list=$('detailEvents');list.replaceChildren();try{const events=await api(`/api/tasks/${t.id}/events`);for(const e of events){const item=node('div','event',e.message);item.append(node('small',null,new Date(e.created_at).toLocaleString()));list.append(item)}if(!events.length)list.append(node('p',null,'No activity yet.'))}catch(err){list.textContent=err.message}$('detailDialog').showModal()}
$('projectSelect').addEventListener('change',async e=>{state.project=state.projects.find(p=>p.id===Number(e.target.value));await renderProject()});
$('newProject').addEventListener('click',()=>$('projectDialog').showModal());$('newTask').addEventListener('click',()=>$('taskDialog').showModal());
for(const button of document.querySelectorAll('[data-close]'))button.addEventListener('click',()=>button.closest('dialog').close());
$('projectForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{const p=await api('/api/projects',{method:'POST',body:JSON.stringify(data)});form.reset();$('projectDialog').close();await loadProjects();state.project=p;$('projectSelect').value=p.id;await renderProject();toast('Project created')}catch(err){form.querySelector('.form-error').textContent=err.message}});
$('taskForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{await api(`/api/projects/${state.project.id}/tasks`,{method:'POST',body:JSON.stringify(data)});form.reset();$('taskDialog').close();await renderProject();toast('Task created')}catch(err){form.querySelector('.form-error').textContent=err.message}});
loadProjects().catch(err=>toast(err.message));
